export const projects = [
	{
		id: 5,
		url: "mothers-birth-doula",
		name: "Mother's Birth Doula",
		imgs: [
			"../assets/project-imgs/mbd/landing.png",
			"../assets/project-imgs/mbd/about page.png",
			"../assets/project-imgs/mbd/services page.png",
			"../assets/project-imgs/mbd/contact page.png",
			"../assets/project-imgs/mbd/modal.png",
		],
		text: "now this one will blow your mind even more than the past.",
		technologies: ["HTML", "SCSS", "React.js", "React Router", "AOS", "Adobe Illustrator"],
	},
	{
		id: 4,
		url: "drk-clothing",
		name: "Drk Clothing",
		imgs: [
			"../assets/project-imgs/drk-clothing/landing.png",
			"../assets/project-imgs/drk-clothing/shop page.png",
			"../assets/project-imgs/drk-clothing/product page.png",
			"../assets/project-imgs/drk-clothing/sign in page.png",
			"../assets/project-imgs/drk-clothing/checkout page.png",
		],
		text: "now this one will blow your mind even more than the past.",
		technologies: [
			"HTML",
			"SCSS",
			"React.js",
			"React Router",
			"React Redux",
			"React Redux Toolkit",
			"Redux Logger",
			"Firebase",
			"Stripe",
			"Styled Components",
		],
	},
	{
		id: 3,
		url: "gatsby-blog",
		name: "Gatsby Blog",
		imgs: ["gatsby-blog/landing.png"],
		text: "now this one will blow your mind even more than the past.",
		technologies: ["HTML", "Gatsby.js", "Gatsby Transformer Remark", "Styled Components"],
	},
	{
		id: 2,
		url: "aleb",
		name: "aleb",
		imgs: [
			"../assets/project-imgs/aleb/full_design.png",
			"../assets/project-imgs/aleb/home_page_1080.png",
			"../assets/project-imgs/aleb/about_page_1080.png",
			"../assets/project-imgs/aleb/mobile_dark.png",
			"../assets/project-imgs/aleb/mobile_light.png",
		],
		text: "now this one will blow your mind even more than the past.",
		technologies: ["HTML", "SCSS", "React.js", "i18next", "AOS", "React Router", "Adobe Illustrator"],
	},
	{
		id: 1,
		url: "suna-dubios",
		name: "Suna dubios",
		imgs: [
			"../assets/project-imgs/suna-dubios/SD_box.jpg",
			"../assets/project-imgs/suna-dubios/SD_on-the-table.jpg",
			"../assets/project-imgs/suna-dubios/SD_question-cards.jpg",
			"../assets/project-imgs/suna-dubios/SD_user-cards.jpg",
		],
		text: "this is my first project and i'm so proud of it.",
	},
];
